<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $employees = Employee::all();
        return view('employees.index', compact('employees'));
    }

    /**
     * Get data for DevExtreme DataGrid (AJAX)
     */
    public function getData(Request $request)
    {
        $employees = Employee::with(['department', 'currentRoom.room'])->get();
        return response()->json($employees);
    }

    /**
     * Show the specified resource (for checking current room)
     */
    public function show(Employee $employee)
    {
        $employee->load('currentRoom.room');

        // Format response with current_room data
        $response = $employee->toArray();
        if ($employee->currentRoom) {
            $response['current_room'] = [
                'id' => $employee->currentRoom->room->id,
                'room_code' => $employee->currentRoom->room->room_code,
                'check_in_date' => $employee->currentRoom->check_in_date
            ];
        } else {
            $response['current_room'] = null;
        }

        return response()->json($response);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'department_id' => 'required|exists:departments,id',
            'status' => 'required|in:Aktif,Non-aktif'
        ]);

        // employee_id will be auto-generated by model

        $employee = Employee::create($validated);
        $employee->load('department');

        return response()->json([
            'success' => true,
            'message' => 'Karyawan berhasil ditambahkan dengan ID: ' . $employee->employee_id,
            'data' => $employee
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Employee $employee)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'department_id' => 'required|exists:departments,id',
            'status' => 'required|in:Aktif,Non-aktif'
        ]);

        // Validate: Cannot change status to Non-aktif if employee is currently occupying a room
        if ($validated['status'] === 'Non-aktif' && $employee->status === 'Aktif') {
            $currentRoom = $employee->currentRoom;
            if ($currentRoom) {
                return response()->json([
                    'success' => false,
                    'message' => 'Tidak dapat mengubah status menjadi Non-aktif. Karyawan masih menempati kamar ' . $currentRoom->room->room_code . '. Lakukan checkout terlebih dahulu.'
                ], 400);
            }
        }

        $employee->update($validated);
        $employee->load('department');

        return response()->json([
            'success' => true,
            'message' => 'Data karyawan berhasil diupdate',
            'data' => $employee
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        return response()->json([
            'success' => true,
            'message' => 'Karyawan berhasil dihapus'
        ]);
    }
}
